"""initial_storage_schema

Revision ID: fcefb6533b1c
Revises:
Create Date: 2026-08-29 13:20:22.711726
"""

from collections.abc import Sequence

import sqlalchemy as sa

import szs_hub.storage.base
from alembic import op

revision: str = "fcefb6533b1c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("source_fingerprint", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("started_at", szs_hub.storage.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("completed_at", szs_hub.storage.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("stats", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed', 'cancelled')",
            name=op.f("ck_import_runs_valid_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_runs")),
        sa.UniqueConstraint("source_fingerprint", name=op.f("uq_import_runs_source_fingerprint")),
    )
    with op.batch_alter_table("import_runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_import_runs_status_started", ["status", "started_at"], unique=False
        )

    op.create_table(
        "inbox_updates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("update_id", sa.BigInteger(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "received_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "available_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("claimed_at", szs_hub.storage.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("processed_at", szs_hub.storage.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_inbox_updates_attempts_nonnegative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inbox_updates")),
        sa.UniqueConstraint("update_id", name=op.f("uq_inbox_updates_update_id")),
    )
    with op.batch_alter_table("inbox_updates", schema=None) as batch_op:
        batch_op.create_index(
            "ix_inbox_updates_ready", ["processed_at", "available_at", "received_at"], unique=False
        )

    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.String(length=100), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column(
            "run_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="5", nullable=False),
        sa.Column("locked_at", szs_hub.storage.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("locked_until", szs_hub.storage.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=128), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("completed_at", szs_hub.storage.base.UTCDateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed', 'cancelled')",
            name=op.f("ck_jobs_valid_status"),
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_jobs_attempts_nonnegative")),
        sa.CheckConstraint("max_attempts > 0", name=op.f("ck_jobs_max_attempts_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_jobs_idempotency_key")),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index("ix_jobs_lease", ["status", "locked_until"], unique=False)
        batch_op.create_index("ix_jobs_ready", ["status", "run_at"], unique=False)

    op.create_table(
        "media_groups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_media_group_id", sa.String(length=128), nullable=False),
        sa.Column(
            "first_message_at", szs_hub.storage.base.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("finalized_at", szs_hub.storage.base.UTCDateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_groups")),
        sa.UniqueConstraint(
            "chat_id",
            "telegram_media_group_id",
            name=op.f("uq_media_groups_chat_id_telegram_media_group_id"),
        ),
    )
    with op.batch_alter_table("media_groups", schema=None) as batch_op:
        batch_op.create_index(
            "ix_media_groups_chat_received", ["chat_id", "first_message_at"], unique=False
        )

    op.create_table(
        "schedule_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("group_key", sa.String(length=128), nullable=False),
        sa.Column("fetched_at", szs_hub.storage.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("is_complete", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("raw_payload", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_snapshots")),
        sa.UniqueConstraint(
            "source",
            "group_key",
            "content_hash",
            name=op.f("uq_schedule_snapshots_source_group_key_content_hash"),
        ),
    )
    with op.batch_alter_table("schedule_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "ix_schedule_snapshots_group_fetched", ["group_key", "fetched_at"], unique=False
        )

    op.create_table(
        "search_documents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("embedding", sa.LargeBinary(), nullable=True),
        sa.Column(
            "updated_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_documents")),
        sa.UniqueConstraint(
            "source_type", "source_id", name=op.f("uq_search_documents_source_type_source_id")
        ),
    )
    with op.batch_alter_table("search_documents", schema=None) as batch_op:
        batch_op.create_index("ix_search_documents_updated_at", ["updated_at"], unique=False)

    op.create_table(
        "topics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("thread_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=True),
        sa.Column("is_closed", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topics")),
        sa.UniqueConstraint("chat_id", "thread_id", name=op.f("uq_topics_chat_id_thread_id")),
    )
    with op.batch_alter_table("topics", schema=None) as batch_op:
        batch_op.create_index("ix_topics_chat_kind", ["chat_id", "kind"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("display_name", sa.String(length=256), nullable=True),
        sa.Column("language_code", sa.String(length=16), nullable=True),
        sa.Column("is_bot", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "first_seen_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("telegram_user_id", name=op.f("uq_users_telegram_user_id")),
    )
    op.create_table(
        "admin_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=True),
        sa.Column("target_id", sa.String(length=256), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_admin_events_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_events")),
    )
    with op.batch_alter_table("admin_events", schema=None) as batch_op:
        batch_op.create_index("ix_admin_events_created_at", ["created_at"], unique=False)
        batch_op.create_index(
            "ix_admin_events_type_created", ["event_type", "created_at"], unique=False
        )

    op.create_table(
        "ai_conversations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column(
            "created_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", szs_hub.storage.base.UTCDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_ai_conversations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_conversations")),
    )
    with op.batch_alter_table("ai_conversations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_ai_conversations_user_updated", ["user_id", "updated_at"], unique=False
        )

    op.create_table(
        "lessons",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("lesson_key", sa.String(length=128), nullable=False),
        sa.Column("source_id", sa.String(length=256), nullable=True),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("starts_at", sa.Time(), nullable=False),
        sa.Column("ends_at", sa.Time(), nullable=False),
        sa.Column("subject", sa.String(length=512), nullable=False),
        sa.Column("lesson_type", sa.String(length=128), nullable=True),
        sa.Column("teacher", sa.String(length=256), nullable=True),
        sa.Column("room", sa.String(length=128), nullable=True),
        sa.Column("building", sa.String(length=128), nullable=True),
        sa.Column("subgroup", sa.String(length=128), nullable=True),
        sa.CheckConstraint("ends_at > starts_at", name=op.f("ck_lessons_positive_duration")),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["schedule_snapshots.id"],
            name=op.f("fk_lessons_snapshot_id_schedule_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lessons")),
        sa.UniqueConstraint(
            "snapshot_id", "lesson_key", name=op.f("uq_lessons_snapshot_id_lesson_key")
        ),
    )
    with op.batch_alter_table("lessons", schema=None) as batch_op:
        batch_op.create_index("ix_lessons_day_time", ["day", "starts_at"], unique=False)
        batch_op.create_index("ix_lessons_snapshot_day", ["snapshot_id", "day"], unique=False)

    op.create_table(
        "memberships",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="unknown", nullable=False),
        sa.Column("is_headman", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("joined_at", szs_hub.storage.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("left_at", szs_hub.storage.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column(
            "checked_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('creator', 'administrator', 'member', 'restricted', "
            "'left', 'kicked', 'unknown')",
            name=op.f("ck_memberships_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint("chat_id", "user_id", name=op.f("uq_memberships_chat_id_user_id")),
    )
    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.create_index("ix_memberships_chat_status", ["chat_id", "status"], unique=False)

    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=True),
        sa.Column("sender_user_id", sa.Integer(), nullable=True),
        sa.Column("media_group_id", sa.Integer(), nullable=True),
        sa.Column("reply_to_message_id", sa.BigInteger(), nullable=True),
        sa.Column("source", sa.String(length=24), server_default="bot_api", nullable=False),
        sa.Column("message_type", sa.String(length=32), server_default="unknown", nullable=False),
        sa.Column("sender_display_name", sa.String(length=256), nullable=True),
        sa.Column("forward_metadata", sa.JSON(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("entities", sa.JSON(), nullable=True),
        sa.Column("sent_at", szs_hub.storage.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("edited_at", szs_hub.storage.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", szs_hub.storage.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column(
            "ingested_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('bot_api', 'telegram_export')", name=op.f("ck_messages_valid_source")
        ),
        sa.ForeignKeyConstraint(
            ["media_group_id"],
            ["media_groups.id"],
            name=op.f("fk_messages_media_group_id_media_groups"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sender_user_id"],
            ["users.id"],
            name=op.f("fk_messages_sender_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name=op.f("fk_messages_topic_id_topics"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint("chat_id", "message_id", name=op.f("uq_messages_chat_id_message_id")),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index("ix_messages_media_group", ["media_group_id"], unique=False)
        batch_op.create_index(
            "ix_messages_sender_sent", ["sender_user_id", "sent_at"], unique=False
        )
        batch_op.create_index("ix_messages_sent_at", ["sent_at"], unique=False)
        batch_op.create_index("ix_messages_topic_sent", ["topic_id", "sent_at"], unique=False)
        batch_op.create_index("ix_messages_type_sent", ["message_type", "sent_at"], unique=False)

    op.create_table(
        "outbox",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=100), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column(
            "available_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="5", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("telegram_message_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("sent_at", szs_hub.storage.base.UTCDateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'sending', 'sent', 'failed', 'cancelled')",
            name=op.f("ck_outbox_valid_status"),
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_outbox_attempts_nonnegative")),
        sa.CheckConstraint("max_attempts > 0", name=op.f("ck_outbox_max_attempts_positive")),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_outbox_job_id_jobs"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_outbox_idempotency_key")),
    )
    with op.batch_alter_table("outbox", schema=None) as batch_op:
        batch_op.create_index("ix_outbox_ready", ["status", "available_at"], unique=False)

    op.create_table(
        "processed_updates",
        sa.Column("update_id", sa.BigInteger(), nullable=False),
        sa.Column("handler", sa.String(length=100), nullable=False),
        sa.Column("outcome", sa.String(length=16), server_default="processed", nullable=False),
        sa.Column(
            "processed_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "outcome IN ('processed', 'ignored', 'failed')",
            name=op.f("ck_processed_updates_valid_outcome"),
        ),
        sa.ForeignKeyConstraint(
            ["update_id"],
            ["inbox_updates.update_id"],
            name=op.f("fk_processed_updates_update_id_inbox_updates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("update_id", name=op.f("pk_processed_updates")),
    )
    with op.batch_alter_table("processed_updates", schema=None) as batch_op:
        batch_op.create_index("ix_processed_updates_processed_at", ["processed_at"], unique=False)

    op.create_table(
        "system_settings",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_by_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_system_settings_updated_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_system_settings")),
    )
    op.create_table(
        "ai_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("sources", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('system', 'user', 'assistant', 'tool')",
            name=op.f("ck_ai_messages_valid_role"),
        ),
        sa.CheckConstraint(
            "token_count IS NULL OR token_count >= 0",
            name=op.f("ck_ai_messages_token_count_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["ai_conversations.id"],
            name=op.f("fk_ai_messages_conversation_id_ai_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_messages")),
    )
    with op.batch_alter_table("ai_messages", schema=None) as batch_op:
        batch_op.create_index(
            "ix_ai_messages_conversation_created", ["conversation_id", "created_at"], unique=False
        )

    op.create_table(
        "attendance_sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("reaction", sa.String(length=32), server_default="❤", nullable=False),
        sa.Column("opens_at", szs_hub.storage.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("closes_at", szs_hub.storage.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="scheduled", nullable=False),
        sa.Column(
            "created_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('scheduled', 'open', 'closed', 'cancelled')",
            name=op.f("ck_attendance_sessions_valid_status"),
        ),
        sa.CheckConstraint(
            "closes_at > opens_at", name=op.f("ck_attendance_sessions_positive_window")
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
            name=op.f("fk_attendance_sessions_lesson_id_lessons"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendance_sessions")),
        sa.UniqueConstraint(
            "chat_id", "message_id", name=op.f("uq_attendance_sessions_chat_id_message_id")
        ),
        sa.UniqueConstraint("lesson_id", name=op.f("uq_attendance_sessions_lesson_id")),
    )
    with op.batch_alter_table("attendance_sessions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_attendance_sessions_status_window",
            ["status", "opens_at", "closes_at"],
            unique=False,
        )

    op.create_table(
        "files",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("telegram_file_id", sa.String(length=512), nullable=False),
        sa.Column("telegram_file_unique_id", sa.String(length=256), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=True),
        sa.Column("file_name", sa.String(length=512), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("storage_path", sa.Text(), nullable=True),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "size_bytes IS NULL OR size_bytes >= 0", name=op.f("ck_files_size_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_files_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_files")),
        sa.UniqueConstraint(
            "message_id",
            "telegram_file_unique_id",
            name=op.f("uq_files_message_id_telegram_file_unique_id"),
        ),
    )
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.create_index("ix_files_kind", ["kind"], unique=False)
        batch_op.create_index("ix_files_unique_id", ["telegram_file_unique_id"], unique=False)

    op.create_table(
        "materials",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_message_id", sa.Integer(), nullable=False),
        sa.Column("source_media_group_id", sa.Integer(), nullable=True),
        sa.Column("destination_chat_id", sa.BigInteger(), nullable=True),
        sa.Column("destination_message_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("discipline", sa.String(length=256), nullable=True),
        sa.Column("material_type", sa.String(length=32), server_default="unknown", nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "workflow_state",
            sa.String(length=24),
            server_default="discovered",
            nullable=False,
        ),
        sa.Column("classifier_version", sa.String(length=64), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "workflow_state IN ('discovered', 'review', 'copy_pending', 'copied', "
            "'delete_pending', 'completed', 'failed')",
            name=op.f("ck_materials_valid_workflow_state"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_materials_valid_confidence")
        ),
        sa.ForeignKeyConstraint(
            ["source_media_group_id"],
            ["media_groups.id"],
            name=op.f("fk_materials_source_media_group_id_media_groups"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_message_id"],
            ["messages.id"],
            name=op.f("fk_materials_source_message_id_messages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_materials")),
        sa.UniqueConstraint("source_message_id", name=op.f("uq_materials_source_message_id")),
    )
    with op.batch_alter_table("materials", schema=None) as batch_op:
        batch_op.create_index("ix_materials_discipline", ["discipline"], unique=False)
        batch_op.create_index(
            "ix_materials_type_created", ["material_type", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_materials_workflow", ["workflow_state", "updated_at"], unique=False
        )

    op.create_table(
        "schedule_changes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("from_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("to_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("before_lesson_id", sa.Integer(), nullable=True),
        sa.Column("after_lesson_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "detected_at",
            szs_hub.storage.base.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("notified_at", szs_hub.storage.base.UTCDateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('added', 'cancelled', 'time', 'room', 'building', 'teacher', "
            "'lesson_type', 'subject')",
            name=op.f("ck_schedule_changes_valid_kind"),
        ),
        sa.CheckConstraint(
            "before_lesson_id IS NOT NULL OR after_lesson_id IS NOT NULL",
            name=op.f("ck_schedule_changes_has_lesson"),
        ),
        sa.ForeignKeyConstraint(
            ["after_lesson_id"],
            ["lessons.id"],
            name=op.f("fk_schedule_changes_after_lesson_id_lessons"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["before_lesson_id"],
            ["lessons.id"],
            name=op.f("fk_schedule_changes_before_lesson_id_lessons"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["from_snapshot_id"],
            ["schedule_snapshots.id"],
            name=op.f("fk_schedule_changes_from_snapshot_id_schedule_snapshots"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_snapshot_id"],
            ["schedule_snapshots.id"],
            name=op.f("fk_schedule_changes_to_snapshot_id_schedule_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_changes")),
        sa.UniqueConstraint(
            "to_snapshot_id",
            "fingerprint",
            name=op.f("uq_schedule_changes_to_snapshot_id_fingerprint"),
        ),
    )
    with op.batch_alter_table("schedule_changes", schema=None) as batch_op:
        batch_op.create_index(
            "ix_schedule_changes_pending", ["notified_at", "detected_at"], unique=False
        )

    op.create_table(
        "attendance_marks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("source_update_id", sa.BigInteger(), nullable=True),
        sa.Column("marked_at", szs_hub.storage.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("removed_at", szs_hub.storage.base.UTCDateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "removed_at IS NULL OR removed_at >= marked_at",
            name=op.f("ck_attendance_marks_valid_removal_time"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["attendance_sessions.id"],
            name=op.f("fk_attendance_marks_session_id_attendance_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_update_id"],
            ["inbox_updates.update_id"],
            name=op.f("fk_attendance_marks_source_update_id_inbox_updates"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_attendance_marks_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendance_marks")),
        sa.UniqueConstraint(
            "session_id", "user_id", name=op.f("uq_attendance_marks_session_id_user_id")
        ),
    )
    with op.batch_alter_table("attendance_marks", schema=None) as batch_op:
        batch_op.create_index(
            "ix_attendance_marks_user_marked", ["user_id", "marked_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attendance_marks", schema=None) as batch_op:
        batch_op.drop_index("ix_attendance_marks_user_marked")

    op.drop_table("attendance_marks")
    with op.batch_alter_table("schedule_changes", schema=None) as batch_op:
        batch_op.drop_index("ix_schedule_changes_pending")

    op.drop_table("schedule_changes")
    with op.batch_alter_table("materials", schema=None) as batch_op:
        batch_op.drop_index("ix_materials_workflow")
        batch_op.drop_index("ix_materials_type_created")
        batch_op.drop_index("ix_materials_discipline")

    op.drop_table("materials")
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.drop_index("ix_files_unique_id")
        batch_op.drop_index("ix_files_kind")

    op.drop_table("files")
    with op.batch_alter_table("attendance_sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_attendance_sessions_status_window")

    op.drop_table("attendance_sessions")
    with op.batch_alter_table("ai_messages", schema=None) as batch_op:
        batch_op.drop_index("ix_ai_messages_conversation_created")

    op.drop_table("ai_messages")
    op.drop_table("system_settings")
    with op.batch_alter_table("processed_updates", schema=None) as batch_op:
        batch_op.drop_index("ix_processed_updates_processed_at")

    op.drop_table("processed_updates")
    with op.batch_alter_table("outbox", schema=None) as batch_op:
        batch_op.drop_index("ix_outbox_ready")

    op.drop_table("outbox")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index("ix_messages_type_sent")
        batch_op.drop_index("ix_messages_topic_sent")
        batch_op.drop_index("ix_messages_sent_at")
        batch_op.drop_index("ix_messages_sender_sent")
        batch_op.drop_index("ix_messages_media_group")

    op.drop_table("messages")
    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.drop_index("ix_memberships_chat_status")

    op.drop_table("memberships")
    with op.batch_alter_table("lessons", schema=None) as batch_op:
        batch_op.drop_index("ix_lessons_snapshot_day")
        batch_op.drop_index("ix_lessons_day_time")

    op.drop_table("lessons")
    with op.batch_alter_table("ai_conversations", schema=None) as batch_op:
        batch_op.drop_index("ix_ai_conversations_user_updated")

    op.drop_table("ai_conversations")
    with op.batch_alter_table("admin_events", schema=None) as batch_op:
        batch_op.drop_index("ix_admin_events_type_created")
        batch_op.drop_index("ix_admin_events_created_at")

    op.drop_table("admin_events")
    op.drop_table("users")
    with op.batch_alter_table("topics", schema=None) as batch_op:
        batch_op.drop_index("ix_topics_chat_kind")

    op.drop_table("topics")
    with op.batch_alter_table("search_documents", schema=None) as batch_op:
        batch_op.drop_index("ix_search_documents_updated_at")

    op.drop_table("search_documents")
    with op.batch_alter_table("schedule_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_schedule_snapshots_group_fetched")

    op.drop_table("schedule_snapshots")
    with op.batch_alter_table("media_groups", schema=None) as batch_op:
        batch_op.drop_index("ix_media_groups_chat_received")

    op.drop_table("media_groups")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_jobs_ready")
        batch_op.drop_index("ix_jobs_lease")

    op.drop_table("jobs")
    with op.batch_alter_table("inbox_updates", schema=None) as batch_op:
        batch_op.drop_index("ix_inbox_updates_ready")

    op.drop_table("inbox_updates")
    with op.batch_alter_table("import_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_import_runs_status_started")

    op.drop_table("import_runs")
    # ### end Alembic commands ###
