"""Public persistence API."""

from szs_hub.storage.base import Base, UTCDateTime, utc_now
from szs_hub.storage.database import (
    SQLiteJournalMode,
    UnsafeSQLiteVersionError,
    create_database_engine,
    create_schema,
    create_session_factory,
    select_sqlite_journal_mode,
    session_scope,
    sqlite_wal_is_safe,
)
from szs_hub.storage.fts import SearchHit, SearchRepository, build_safe_match_query
from szs_hub.storage.inbox import enqueue_raw_update, record_processed_update
from szs_hub.storage.models import (
    AdminEvent,
    AIConversation,
    AIMessage,
    AttendanceMark,
    AttendanceSession,
    File,
    ImportRun,
    InboxUpdate,
    Job,
    Lesson,
    Material,
    MediaGroup,
    Membership,
    Message,
    OutboxMessage,
    ProcessedUpdate,
    ScheduleChange,
    ScheduleSnapshot,
    SearchDocument,
    SystemSetting,
    Topic,
    User,
)

__all__ = [
    "AIConversation",
    "AIMessage",
    "AdminEvent",
    "AttendanceMark",
    "AttendanceSession",
    "Base",
    "File",
    "ImportRun",
    "InboxUpdate",
    "Job",
    "Lesson",
    "Material",
    "MediaGroup",
    "Membership",
    "Message",
    "OutboxMessage",
    "ProcessedUpdate",
    "SQLiteJournalMode",
    "ScheduleChange",
    "ScheduleSnapshot",
    "SearchHit",
    "SearchRepository",
    "SearchDocument",
    "SystemSetting",
    "Topic",
    "UTCDateTime",
    "UnsafeSQLiteVersionError",
    "User",
    "create_database_engine",
    "create_schema",
    "create_session_factory",
    "build_safe_match_query",
    "enqueue_raw_update",
    "record_processed_update",
    "select_sqlite_journal_mode",
    "session_scope",
    "sqlite_wal_is_safe",
    "utc_now",
]
